# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(help_text='Recorded date')),
                ('duration', models.IntegerField(help_text='Jogging duration in seconds')),
                ('distance', models.FloatField(help_text='Jogging distance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user.User')),
            ],
        ),
    ]
