# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 11:20
from __future__ import unicode_literals

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
